In [1]:
#import liberaries
import pandas as pd
import re

#### [0-9]{2}_\d{3}\s[^a-z](,6}
        56_654 ASD23 

#### AB123 123abcd
    \w{2}\d{3}\s\d{3}\w{4}

In [2]:
#load data

In [6]:
data4 = pd.read_csv("C:\\Users\\EMZ\\Desktop\\JeelAIDM\\NLP\\Data4.csv",header=None)
data4.columns=["email"]
data4

                                 email
0     my email is  nlp1_2010@yahoo.com
1     my email is  nlp2_2011@yahoo.com
2     my email is  nlp3_2012@yahoo.com
3     my email is  nlp4_2013@yahoo.com
4     my email is  nlp5_2014@yahoo.net
5     my email is  nlp6_2015@yahoo.net
6     my email is  nlp7_2016@yahoo.net
7     my email is  nlp8_2017@gmail.net
8     my email is  nlp9_2018@gmail.net
9    my email is  nlp10_2019@gmail.net
10  my email is  nlp11_2020@gmail.info
11  my email is  nlp12_2021@gmail.info
12   my email is  nlp132010@gmail.info
13   my email is  nlp142011@gmail.info
14   my email is  nlp152012@gmail.info
15  my email is  nlp162013@hotmail.org
16     my email is  nlp172014yahoo.org
17     my email is  nlp182015yahoo.org
18     my email is  nlp192016gmail.org
19     my email is  nlp202017gmail.org
20      my email is  nlp212018gmailcom
21      my email is  nlp22.AI@gmailcom
22      my email is  nlp23.AI@gmailcom
23      my email is  nlp24.AI@gmailcom
24      my email is  nlp25.AI@gmailnet
25      my email is  nlp26.AI@yahoonet
26      my email is  nlp27.AI@yahoonet
27      my email is  nlp28.AI@yahoonet
28                        my email is

In [16]:
for row in data4["email"]:
    valid_email = re.findall(r'^[a-z 0-9]+[\._?][a-z 0-9]+[@]\w+[.]+\w+$',row)
    if valid_email:
        print(valid_email)

['my email is  nlp1_2010@yahoo.com']
['my email is  nlp2_2011@yahoo.com']
['my email is  nlp3_2012@yahoo.com']
['my email is  nlp4_2013@yahoo.com']
['my email is  nlp5_2014@yahoo.net']
['my email is  nlp6_2015@yahoo.net']
['my email is  nlp7_2016@yahoo.net']
['my email is  nlp8_2017@gmail.net']
['my email is  nlp9_2018@gmail.net']
['my email is  nlp10_2019@gmail.net']
['my email is  nlp11_2020@gmail.info']
['my email is  nlp12_2021@gmail.info']

In [ ]:
#email= data4["email"]
# pattern =  '^[a-z 0-9]+[\._?][a-z 0-9]+[@]\w+[.]\w{2,3}$'
#valid_email = re.findall(r'[\w\.-]+@[\w\.-]+.com')

In [20]:
email = data4.loc[data4["email"].str.contains('^[a-z 0-9]+[\._?][a-z 0-9]+[@]\w+[.]+\w+$',regex=True)]

In [21]:
email

                                 email
0     my email is  nlp1_2010@yahoo.com
1     my email is  nlp2_2011@yahoo.com
2     my email is  nlp3_2012@yahoo.com
3     my email is  nlp4_2013@yahoo.com
4     my email is  nlp5_2014@yahoo.net
5     my email is  nlp6_2015@yahoo.net
6     my email is  nlp7_2016@yahoo.net
7     my email is  nlp8_2017@gmail.net
8     my email is  nlp9_2018@gmail.net
9    my email is  nlp10_2019@gmail.net
10  my email is  nlp11_2020@gmail.info
11  my email is  nlp12_2021@gmail.info

In [22]:
email.drop_duplicates()

                                 email
0     my email is  nlp1_2010@yahoo.com
1     my email is  nlp2_2011@yahoo.com
2     my email is  nlp3_2012@yahoo.com
3     my email is  nlp4_2013@yahoo.com
4     my email is  nlp5_2014@yahoo.net
5     my email is  nlp6_2015@yahoo.net
6     my email is  nlp7_2016@yahoo.net
7     my email is  nlp8_2017@gmail.net
8     my email is  nlp9_2018@gmail.net
9    my email is  nlp10_2019@gmail.net
10  my email is  nlp11_2020@gmail.info
11  my email is  nlp12_2021@gmail.info

In [ ]:
email.to_csv("C:\\Users\\EMZ\\Desktop\\JeelAIDM\\NLP\\email.csv")

In [ ]:
#for row in range (0,len(data4)):
   # valid_email = re.search